CREATE TABLE PatientCheckup (
	PatientID varchar(255) NOT NULL,
    DOC date NOT NULL,
    Cold varchar(5) DEFAULT 'No' NOT NULL,
    ColdDuration int DEFAULT 0 NOT NULL,
    Cough varchar(5) DEFAULT 'No' NOT NULL,
    CoughType varchar(20) DEFAULT 'No' NOT NULL,
    CoughDuration int DEFAULT 0 NOT NULL,
    SOB varchar(5) DEFAULT 'No' NOT NULL,
    SOBDuration int DEFAULT 0,
    Fever varchar(5) DEFAULT 'No' NOT NULL,
    SoreThroat varchar(5) DEFAULT 'No' NOT NULL,
    TravelHistory varchar(5) DEFAULT 'No' NOT NULL,
    ContactHistory varchar(5) DEFAULT 'No' NOT NULL,
    OtherComplaints varchar(255) DEFAULT '',
    HTN varchar(5) DEFAULT 'No' NOT NULL,
    DM varchar(5) DEFAULT 'No' NOT NULL,
    IHD varchar(5) DEFAULT 'No' NOT NULL,
    Asthma varchar(5) DEFAULT 'No' NOT NULL,
    CLD varchar(5) DEFAULT 'No' NOT NULL,
    Seizure varchar(5) DEFAULT 'No' NOT NULL,
    OtherComorbidities varchar(255)  DEFAULT '',
    Smoking varchar(5) DEFAULT 'No' NOT NULL,
    Alcohol varchar(5) DEFAULT 'No' NOT NULL,
    Gutka varchar(5) DEFAULT 'No' NOT NULL,
    OtherAddictions varchar(255)  DEFAULT '',
    Pallor varchar(5) DEFAULT 'No' NOT NULL,
    Icterus varchar(5) DEFAULT 'No' NOT NULL,
    Clubbing varchar(5) DEFAULT 'No' NOT NULL,
    Cyanosis varchar(5) DEFAULT 'No' NOT NULL,
    Lympadenopathy varchar(5) DEFAULT 'No' NOT NULL,
    Edema  varchar(20) DEFAULT 'No' NOT NULL,
    Temp varchar(20) DEFAULT '' NOT NULL,
    HR varchar(20) DEFAULT '' NOT NULL,
    BP varchar(20) DEFAULT '' NOT NULL,
    RR varchar(20) DEFAULT '' NOT NULL,
    SPO2 varchar(20) DEFAULT '' NOT NULL,
    CNS varchar(20) DEFAULT '' NOT NULL,
    CVS varchar(20) DEFAULT '' NOT NULL,
    RS varchar(20) DEFAULT '' NOT NULL,
    GIT varchar(20) DEFAULT '' NOT NULL,
    OtherSystemic varchar(255)  DEFAULT '',
    Investigation varchar(255)  DEFAULT '',
    Treatment varchar(255)  DEFAULT '',
    InPatient varchar(5)  DEFAULT 'No',
    FollowUp varchar(255)  DEFAULT '',
    PRIMARY KEY(PatientID,DOC),
    FOREIGN KEY (PatientID) REFERENCES Patients(PatientID),
);